version: '3.4'

services:
  comdockerdevenvironments:
    image: comdockerdevenvironments
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd with ñ
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
